spring:
  application:
    name: springboot
mybatis:
  mapper-locations: classpath:sql-mapper/*.xml

server:
  port: 1992

#jwt parameters
jwt:
  header: Authorization
  secret: derrick.yang
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"

security:
  basic:
    enabled: false
management:
  security:
    enabled: false

# 主从库配置
master:
    url: jdbc:mysql://104.224.163.143:3306/test
#    url: jdbc:mysql://localhost:8066/TESTDB
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    type: com.alibaba.druid.pool.DruidDataSource
slave:
    url: jdbc:mysql://45.78.60.201:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    type: com.alibaba.druid.pool.DruidDataSource

